
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: true
    prefer_const_constructors: true
    prefer_final_locals: true
    use_key_in_widget_constructors: true
    always_declare_return_types: true
    cancel_subscriptions: true
    close_sinks: true
    unnecessary_parenthesis: true
    use_super_parameters: true
